on:
  pull_request:
    branches:
    - master
    - develop
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: returntocorp/semgrep-action@v1
      env:
        SEMGREP_TIMEOUT: 120
      with:
        config: >-
          r/python.lang.correctness
          .github/helper/semgrep_rules
        auditOn: opened, edited, reopened
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
